Add Config
melbahja/goph pull request #34
Opened 2022-01-30 14:20 UTC by SmsS4

This pr is to solve https://github.com/melbahja/goph/issues/31

2023-09-16 22:00 UTC, Dentrax commented
Thanks for this! @SmsS4

I tried `NewWithConfigFile()` function but got `open ~/.ssh/identity: no such file or directory` error. Any ideas? 🤔

2023-09-16 22:14 UTC, SmsS4 commented
hmmmm this PRis for 1.5 years ago
I will check it tomorrow :)

2023-09-16 22:18 UTC, Dentrax commented
Thanks for prompt reply! Also it'd be nice to add another function to return only `Auth`:

```go
func GetAuth(host string) (goph.Auth, error) {
	auth, err := goph.Key(ssh_config.Get(host, "IdentityFile"), "")
	if err != nil {
		return nil, fmt.Errorf("get key: %w", err)
	}
	return auth, nil
}
```

2023-09-17 16:30 UTC, melbahja requested changes
Hey thanks for the PR, can you please use return instead of log fatal.

2023-09-17 16:30 UTC, melbahja commented on client.go
> +		log.Fatal(err)
here can you just return the error instead of Fatal exit

2023-09-17 16:30 UTC, melbahja commented on client.go
> +		log.Fatal(err)
Also here

2023-09-17 21:05 UTC, SmsS4 commented
I fixed your comments

2023-09-17 21:08 UTC, SmsS4 commented
> Thanks for prompt reply! Also it'd be nice to add another function to return only `Auth`:
> 
> ```go
> func GetAuth(host string) (goph.Auth, error) {
> 	auth, err := goph.Key(ssh_config.Get(host, "IdentityFile"), "")
> 	if err != nil {
> 		return nil, fmt.Errorf("get key: %w", err)
> 	}
> 	return auth, nil
> }
> ```

I used your code in new commit
thanks

By default `ssh_config.Get(host, "IdentityFile")` returns `~/.ssh/identity` so you have to set `IdentityFile` in ssh config.
for example:
```
Host vpn
	HostName 127.0.0.1
	User test
	IdentityFile /home/demol/.ssh/id_rsa
```

2023-09-18 15:30 UTC, melbahja commented
Hey thanks for the update, 

one more thing if you can use `NewConn` instead of `New` in case of custom port  with fallback to 22.

v2 of this package I should add more configuration options suport

2023-09-18 18:24 UTC, SmsS4 commented
I will update my fork and use `NewConn` instead of `New` (probably tomorrow or day after tomorrow
Thanks @melbahja 
> Hey thanks for the update,
> 
> one more thing if you can use `NewConn` instead of `New` in case of custom port with fallback to 22.
> 
> v2 of this package I should add more configuration options suport

2023-09-18 18:26 UTC, SmsS4 commented
> > By default ssh_config.Get(host, "IdentityFile") returns ~/.ssh/identity so you have to set IdentityFile in ssh config.
> 
> I was wondering if it does make sense to _return an error_ in case if `IdentityFile` is empty or equals to `ssh_config.Default("IdentityFile")`
> 
> Also you'd consider to remove leading and trailing `"`s, I just filed an issue for that: [kevinburke/ssh_config#61](https://github.com/kevinburke/ssh_config/issues/61)
> 
> ```go
> strings.Trim(ssh_config.Get(host, key), "\"")
> ```

It's probably good idea to use `~/.ssh/id_rsa` by default and not `~/.ssh/identity`  but I only return error if `~/.ssh/identity` doesn't exists.
I will update this soon @Dentrax

2023-09-20 21:00 UTC, SmsS4 commented
@melbahja 
I used NewConn instead of New with a little bit of refactoring

2023-09-22 23:24 UTC, melbahja commented
I'll need a bit of time to test the changes. Thanks.

2023-09-29 13:50 UTC, mehrdad-khojastefar commented
Can you review these changes ? this pr could really help us.

2023-09-29 18:10 UTC, melbahja commented
The `ssh_config` lib has many issues like:
- can't find the default IdentityFile if not set in the config file.
- if your `~/.ssh/config` or '/etc/ssh/ssh_config' file contains `Include` the lib `Get` will always returns empty values
- @Dentrax issue will still exists even with Trim bcz the fallbacks to not exists file `~/.ssh/identity`, see: https://github.com/kevinburke/ssh_config/blob/974a52c2c04b3e24e189311ef9776b87153dd961/validators.go#L120

I think you should solve the ssh config problem outside of goph and just pass the hostname, port, and identity to it, and I don't think this is a good think to add it to v1 maybe in v2.

2026-07-15 20:39 UTC, melbahja commented
@SmsS4 I really appreciate you putting this together,

just closed #31 and decided SSH config parsing is intentionally out of scope for goph. There are too many edge cases that would bloat a library meant to be a thin.

If users want config support, the recommended approach is to use a dedicated parser like `github.com/kevinburke/ssh_config` and pass the results into goph

Going to close, thanks again! 🙏

2026-07-15 20:39 UTC, closed without merging